### ISSUE TITLE
When logs directory missing server won't start

### ISSUE THREAD

**Issue by AKST** [ITatJCU/hunter-server#24]
possible do a `mkdir -p logs` on startup? make the `npm start` command something like `mkdir -p logs && node index.js`, or something a bit nicer as there's a probably a better solution.

**FYI**: the `-p` flag in `mkdir` stands for path, so if you do somthing like `mkdir -p ayy/lmao`, then it creates the `ayy` directory if missing, then makes the `lmao` directory in side the `ayy` directory. But also if you do `mkdir logs` and the directory exists, mkdir will exit with an exit code `1`, whereas `mkdir -p logs` just exits with an exit code `0` if the directory already exists.

**Comment by axrs** [comment]
Yeah... I should make it so that...
